apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
      serviceAccountName: {{ .Release.Name }}-operator
      containers:
        - name: operator
          command:
            - /vpn-operator
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          image: {{ .Values.image }}
      {{- if .Values.prometheus }}
          env:
            - name: METRICS_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: metrics
      {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
